# RoboRIO Robotpy config
[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.3.2.1"

# Which extra RobotPy components should be installed
robotpy_extras = [
    "all",
    # "apriltag",
    # "commands2",
    # "cscore",
    # "navx",
    # "pathplannerlib",
    # "phoenix5",
    # "phoenix6",
    # "photonvision",
    # "playingwithfusion",
    # "rev",
    # "romi",
    # "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
]

# Ruff: https://docs.astral.sh/ruff/configuration
[tool.ruff]

line-length    = 88
indent-width   = 4
target-version = "py312"

[tool.ruff.lint]

select = [
    "E",
    "F",
    "RUF",
]
fixable = [
    "ALL",
]

[tool.ruff.format]

quote-style  = "double"
indent-style = "tab"
line-ending  = "lf"
